CREATE TABLE stock_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    item_code VARCHAR(20) NOT NULL UNIQUE,
    item_name VARCHAR(100) NOT NULL,
    market ENUM('KOSPI', 'KOSDAQ', 'NASDAQ', 'NYSE', 'OTHER') NOT NULL,
    theme ENUM('TECH', 'FINANCE', 'HEALTHCARE', 'ENERGY', 'CONSUMER', 'OTHER') NOT NULL,
    price DECIMAL(10,2) NOT NULL,

    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL,
    modified_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    modified_by VARCHAR(255) NOT NULL,

    PRIMARY KEY (id)
);