name: CI - Build & Test with Coverage

on:
	push:
		branches: [ "feature*" ]
	pull_request:
		branches: [ "main" ]

jobs:
	build:
		runs-on: ubuntu-latest

		steps:
			- name: checkout
			  uses: actions/checkout@v3

			- name: set up JDK 17
			  uses: actions/setup-java@v3
			  with:
				  java-version: '17'
				  distribution: 'temurin'

			- name: grant execution permission to gradle wrapper
			  run: chmod +x ./gradlew

			- name: run tests with coverage
			  run: ./gradlew test jacocoTestReport jacocoTestCoverageVerification

			- name: 📊 upload coverage report
			  if: always()
			  uses: actions/upload-artifact@v4
			  with:
				  name: jacoco-report
				  path: build/reports/jacoco/test/html